spring:
  application:
    name: config-server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:


  cloud:
    config:
      server:
        jdbc:
          enabled: true
          default-label: master
          sql: "SELECT \"KEY\", \"VALUE\" FROM CONFIG WHERE APPLICATION=? AND PROFILE=? AND LABEL=?"

        bootstrap: false
  h2:
    console:
      enabled: true



logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG




server:
  port: 9281
