spring:
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 100
        response-timeout: 20s
      routes:
        - id: proxy-to-idcard
          uri: http://localhost:9000
          predicates:
            - Path=/nfiocr/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
            - WrongHeaderFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 15s #이게 default가 1초이기 때문에 에러가 난다
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 80
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 50

    instances:
      myCircuitBreaker:
        base-config: default
management:
  endpoint:
    health:
      show-details: always
    circuitbreakerevents:
      enabled: true

    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - circuitbreakers
          - circuitbreakerevents
          - health
          - prometheus

  metrics:
    export:
      prometheus:
        enabled: true















