spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:9281
      profile: dev
      name: gateway
      label: master
  config:
    import: optional:configserver:http://localhost:9281